language: python
python:
  - "3.8"
node_js:
  - "8"
install:
  - pip install -r requirements.txt
  - ./scripts/build.sh tests
script:
  - pytest --cov-report term --cov=brain
after_script:
  - codecov