version: '3.0'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    network_mode: host

  mq:
    image: rabbitmq
    ports:
      - 5672:5672
    network_mode: host

  server:
    image: brain
    build: .
    depends_on:
      - mq
    ports:
      - 8000:8000
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: ./wait-for-it.sh rabbitmq:5672 -- python -m brain.server run-server 'rabbitmq://0.0.0.0:5672'
    restart: on-failure:5

  pose:
    image: brain
    depends_on:
      - server
      - mq
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: ./wait-for-it.sh rabbitmq:5672 -- python -m brain.parsers run-parser pose 'rabbitmq://0.0.0.0:5672'
    restart: on-failure

  color-image:
    image: brain
    depends_on:
      - server
      - mq
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: ./wait-for-it.sh rabbitmq:5672 -- python -m brain.parsers run-parser color_image 'rabbitmq://0.0.0.0:5672'
    restart: on-failure

  depth-image:
    image: brain
    depends_on:
      - server
      - mq
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: ./wait-for-it.sh rabbitmq:5672 -- python -m brain.parsers run-parser depth_image 'rabbitmq://0.0.0.0:5672'
    restart: on-failure

  feelings:
    image: brain
    depends_on:
      - server
      - mq
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: ./wait-for-it.sh rabbitmq:5672 -- python -m brain.parsers run-parser feelings 'rabbitmq://0.0.0.0:5672'
    restart: on-failure

  saver:
    image: brain
    depends_on:
      - server
      - db
      - mq
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: ./wait-for-it.sh rabbitmq:5672 -- python -m brain.saver run-saver 'mongodb://0.0.0.0:27017' 'rabbitmq://0.0.0.0:5672'
    restart: on-failure

  api:
    image: brain
    depends_on:
      - db
    network_mode: host
    volumes:
      - brain-vol:/brain-data
    command: python -m brain.api run-server
    restart: on-failure

volumes:
  brain-vol: